### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by chetstone** [bsudekum/react-native-color-grabber#1]
Are you interested in adding Android to this library? I have come up with an [Android implementation](https://github.com/chetstone/react-native-palette), and was wondering if you would accept a PR to add the code to this library? It would involve a major javascript API change, exposing a common API for both platforms, probably similar to what I have now. 

If you're not interested, I'll just publish my library separately. 

Cheers.

**Comment by bsudekum** [comment]
@chetstone absolutely, gladly will accept a PR!

**Comment by chetstone** [comment]
Since the author is not responding, I have merged this code (permitted by ISC license) into my [react-native-palette](https://www.npmjs.com/package/react-native-palette) repo.
